AWSTemplateFormatVersion: "2010-09-09"

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "CSS-SSM"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "ssm:DescribeInstanceInformation"
                Resource: "*"
              - Effect: "Allow"
                Action: "logs:*"
                Resource: "arn:aws:logs:*:*:*"

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import boto3
          import os

          ssm = boto3.client('ssm')

          def handler(event, context):
            key = event["key"]
            value = event["value"]

            # get instances
            iil = ssm.describe_instance_information(
              Filters=[
                {
                  'Key': 'tag:'+key,
                  'Values': [value]
                }
              ],
              MaxResults=50)

            instances = []
            for inst in iil['InstanceInformationList']:
              instances.append(inst['InstanceId'])

            print(instances)
            return None

      Description: "Executes 'ls -al' on instances tagged with key/value"
      Runtime: "python3.7"
      FunctionName: "GetInstanceIds"
      Handler: "index.handler"
      MemorySize: 128
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30

  SSMAutomationDocument:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: "Automation"
      Name: "ListRoot"
      Content: |
        {
          "schemaVersion": "0.3",
          "description": "Returns content of root directory of instances with the given tag key and value",
          "parameters": {
            "key": {
              "type": "String",
              "description": "Tag key"
            },
            "value": {
              "type": "String",
              "description": "Tag value"
            }
          },
          "mainSteps": [
            {
              "name": "InvokeLambda",
              "action": "aws:invokeLambdaFunction",
              "onFailure": "Abort",
              "inputs": {
                "FunctionName": "GetInstanceIds",
                "Payload": "{ \"key\": \"{{ key }}\", \"value\": \"{{ value }}\" }"
              }
            },
            {
              "name": "ListRoot",
              "action": "aws:runCommand",
              "inputs": {
                "DocumentName": "AWS-RunShellScript",
                "Targets": [
                  {
                    "Key": "tag:{{ key }}",
                    "Values": [
                      "{{ value }}"
                    ]
                  }
                ],
                "Parameters": {
                  "workingDirectory": "/",
                  "commands": ["ls -al"]
                }
              }
            }
          ],
          "outputs": [
            "ListRoot.CommandId", "ListRoot.Output"
          ]
        }

Outputs:
  Lambda:
    Value: !Ref Lambda
  SSMDocument:
    Value: !Ref SSMAutomationDocument
