AWSTemplateFormatVersion: "2010-09-09"

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "CSS-SSM"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "logs:*"
                Resource: "arn:aws:logs:*:*:*"

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import boto3
          import os

          ssm = boto3.client('ssm')

          def handler(event, context):
            print("foo")

      Description: "Executes 'ls -al' on instances tagged with key/value"
      Runtime: "python3.7"
      FunctionName: "GetInstanceIds"
      Handler: "index.handler"
      MemorySize: 128
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30

Outputs:
  Lambda:
    Value: !Ref Lambda
